version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./docker/app/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["/usr/local/bin/go-cloud-native/wait-for-mysql.sh", "db", "/usr/local/bin/go-cloud-native/init.sh"]
    volumes:
      - ./migrations:/go-cloud-native/migrations
  db:
    build: ./docker/mariadb/
    environment:
      MYSQL_ROOT_PASSWORD: gocloudnative_root_pass
      MYSQL_DATABASE: gocloudnative_db
      MYSQL_USER: gocloudnative_user
      MYSQL_PASSWORD: gocloudnative_pass
    ports:
      - 3306:3306
    restart: always
